-- =============================================================================
-- Stage 2: one consolidated schema migration.
--   * loan lifecycle: loan_status enum, redemption audit columns, renewals
--   * pledged items: loan_items (integer milligrams) + loan_item_photos
--   * KYC on profiles + a private 'kyc' bucket
--   * notices: loan_notices + server-side loans_overdue_as_of()
--
-- Owner decisions recorded here so the reasoning is not lost:
--   * Existing status='closed' rows STAY 'closed'. 'closed' now means "ended,
--     redemption details unknown" (they predate the audit columns); 'redeemed'
--     is reserved for rows written by the Stage 3 redemption RPC, which always
--     records redeemed_on/redeemed_by/closure_balance_paise.
--   * Item photos reuse the existing private 'receipts' bucket under
--     {customer_id}/items/... The five receipts_* policies already require a
--     UUID first path segment and do not constrain the second, so this needs no
--     new storage policy. A separate bucket would have duplicated all five.
--   * NO Aadhaar images are stored, at any time, enforced by a CHECK. UIDAI's
--     Do's and Don'ts for requesting entities forbid storing a photocopy of an
--     Aadhaar letter without redacting the first 8 digits, and this shop has no
--     masking pipeline or Aadhaar Data Vault. last4 is kept for all document
--     types; document images are allowed for pan/voter_id/driving_licence/
--     passport only.
--   * The walk-in blocker is solved OUTSIDE the schema, by an Edge Function
--     calling auth.admin.createUser({ phone, phone_confirm: true }). That keeps
--     profiles.id = auth.uid(), so no RLS policy or storage path changes here.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. Loan lifecycle: status becomes a real enum
-- ---------------------------------------------------------------------------
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'loan_status') THEN
    CREATE TYPE public.loan_status AS ENUM ('active', 'redeemed', 'closed', 'defaulted');
  END IF;
END $$;

-- The baseline declared status with an INLINE unnamed CHECK, so its name was
-- generated by Postgres. Resolve it from the catalog rather than guessing.
DO $$
DECLARE
  v_conname text;
BEGIN
  FOR v_conname IN
    SELECT conname
    FROM pg_constraint
    WHERE conrelid = 'public.loans'::regclass
      AND contype = 'c'
      AND pg_get_constraintdef(oid) ILIKE '%status%'
  LOOP
    EXECUTE format('ALTER TABLE public.loans DROP CONSTRAINT %I', v_conname);
  END LOOP;
END $$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'loans'
      AND column_name = 'status' AND data_type = 'text'
  ) THEN
    -- A text default cannot be cast implicitly during the type change.
    ALTER TABLE public.loans ALTER COLUMN status DROP DEFAULT;
    -- Both live values ('active','closed') are labels of the new enum, so a
    -- plain cast is exact. Anything else raises, which is the honest outcome.
    ALTER TABLE public.loans
      ALTER COLUMN status TYPE public.loan_status
      USING status::public.loan_status;
    ALTER TABLE public.loans
      ALTER COLUMN status SET DEFAULT 'active'::public.loan_status;
  END IF;
END $$;

ALTER TABLE public.loans
  ADD COLUMN IF NOT EXISTS redeemed_on date,
  ADD COLUMN IF NOT EXISTS redeemed_by uuid REFERENCES public.profiles (id) ON DELETE RESTRICT,
  ADD COLUMN IF NOT EXISTS released_to_name text,
  ADD COLUMN IF NOT EXISTS release_note text,
  ADD COLUMN IF NOT EXISTS closure_balance_paise bigint;

COMMENT ON COLUMN public.loans.closure_balance_paise IS
  'Total due at the moment of redemption. Immutable audit figure: a later rate '
  'or term edit must never be able to rewrite what was actually collected.';

ALTER TABLE public.loans
  DROP CONSTRAINT IF EXISTS loans_closure_balance_chk;
ALTER TABLE public.loans
  ADD CONSTRAINT loans_closure_balance_chk
  CHECK (closure_balance_paise IS NULL OR closure_balance_paise >= 0);

-- A redeemed loan must carry its audit snapshot. Legacy 'closed' rows are
-- deliberately exempt: they were closed before these columns existed.
ALTER TABLE public.loans
  DROP CONSTRAINT IF EXISTS loans_redeemed_audit_chk;
ALTER TABLE public.loans
  ADD CONSTRAINT loans_redeemed_audit_chk CHECK (
    status <> 'redeemed'::public.loan_status
    OR (redeemed_on IS NOT NULL AND closure_balance_paise IS NOT NULL)
  );

COMMENT ON COLUMN public.loans.item_name IS
  'DEPRECATED: superseded by public.loan_items. Retained because the admin UI '
  'still reads it. Drop in a later migration once the UI is migrated.';
COMMENT ON COLUMN public.loans.weight_grams IS
  'DEPRECATED: numeric(10,3) float-adjacent liability. Use '
  'public.loan_items.gross_weight_mg / net_weight_mg (integer milligrams).';

-- ---------------------------------------------------------------------------
-- 2. loan_renewals — interest-only renewal after the simple phase
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.loan_renewals (
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  loan_id              uuid NOT NULL REFERENCES public.loans (id) ON DELETE RESTRICT,
  renewed_on           date NOT NULL DEFAULT (timezone('Asia/Kolkata', now()))::date,
  renewed_by           uuid NOT NULL REFERENCES public.profiles (id) ON DELETE RESTRICT,
  interest_paid_paise  bigint NOT NULL,
  new_maturity_on      date NOT NULL,
  note                 text,
  created_at           timestamptz NOT NULL DEFAULT timezone('utc', now()),

  CONSTRAINT loan_renewals_interest_paid_chk CHECK (interest_paid_paise >= 0),
  CONSTRAINT loan_renewals_maturity_after_renewal_chk CHECK (new_maturity_on > renewed_on)
);

CREATE INDEX IF NOT EXISTS loan_renewals_loan_id_idx
  ON public.loan_renewals (loan_id, renewed_on DESC);

ALTER TABLE public.loan_renewals ENABLE ROW LEVEL SECURITY;

-- ---------------------------------------------------------------------------
-- 3. Extend the loan mutation guard for the new enum + audit columns
--    The previous version compared only against the literal 'closed', so
--    'redeemed' and 'defaulted' would have slipped straight past it.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.enforce_loan_mutation_permissions()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    IF NOT public.is_owner() THEN
      RAISE EXCEPTION 'only owner may delete loans';
    END IF;
    RETURN OLD;
  END IF;

  IF public.is_owner() THEN
    RETURN NEW;
  END IF;

  IF NOT public.is_shop_user() THEN
    RAISE EXCEPTION 'not allowed to mutate loans';
  END IF;

  -- Staff may not end a loan by any route.
  IF NEW.status IS DISTINCT FROM OLD.status
     AND NEW.status IN (
       'redeemed'::public.loan_status,
       'closed'::public.loan_status,
       'defaulted'::public.loan_status
     )
  THEN
    RAISE EXCEPTION 'staff may not close, redeem or default loans';
  END IF;

  -- Staff may not write the redemption audit trail, even on an active loan.
  IF NEW.redeemed_on IS DISTINCT FROM OLD.redeemed_on
     OR NEW.redeemed_by IS DISTINCT FROM OLD.redeemed_by
     OR NEW.closure_balance_paise IS DISTINCT FROM OLD.closure_balance_paise
  THEN
    RAISE EXCEPTION 'staff may not write loan redemption fields';
  END IF;

  -- Staff may not edit frozen terms.
  IF NEW.interest_model IS DISTINCT FROM OLD.interest_model
     OR NEW.rate_bps IS DISTINCT FROM OLD.rate_bps
     OR NEW.simple_period_days IS DISTINCT FROM OLD.simple_period_days
     OR NEW.compound_every_days IS DISTINCT FROM OLD.compound_every_days
     OR NEW.grace_days IS DISTINCT FROM OLD.grace_days
     OR NEW.partial_period_mode IS DISTINCT FROM OLD.partial_period_mode
     OR NEW.round_up_threshold_days IS DISTINCT FROM OLD.round_up_threshold_days
  THEN
    RAISE EXCEPTION 'staff may not edit loan terms';
  END IF;

  RETURN NEW;
END;
$$;

-- ---------------------------------------------------------------------------
-- 4. Pledged items — integer milligrams, one row per ornament
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.loan_items (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  -- CASCADE: an item has no meaning without its loan, and only an owner can
  -- delete a loan in the first place (loans_owner_delete + the trigger above).
  loan_id             uuid NOT NULL REFERENCES public.loans (id) ON DELETE CASCADE,
  ornament_type       text NOT NULL,
  description         text,
  gross_weight_mg     bigint NOT NULL,
  net_weight_mg       bigint NOT NULL,
  purity_karat        smallint,
  stone_deduction_mg  bigint NOT NULL DEFAULT 0,
  quantity            smallint NOT NULL DEFAULT 1,
  valuation_paise     bigint,
  created_at          timestamptz NOT NULL DEFAULT timezone('utc', now()),

  CONSTRAINT loan_items_gross_weight_chk CHECK (gross_weight_mg > 0),
  CONSTRAINT loan_items_net_weight_chk CHECK (net_weight_mg > 0),
  CONSTRAINT loan_items_net_not_over_gross_chk CHECK (net_weight_mg <= gross_weight_mg),
  CONSTRAINT loan_items_stone_deduction_chk CHECK (stone_deduction_mg >= 0),
  CONSTRAINT loan_items_purity_karat_chk CHECK (
    purity_karat IS NULL OR (purity_karat BETWEEN 1 AND 24)
  ),
  CONSTRAINT loan_items_quantity_chk CHECK (quantity >= 1),
  CONSTRAINT loan_items_valuation_chk CHECK (valuation_paise IS NULL OR valuation_paise >= 0)
);

COMMENT ON COLUMN public.loan_items.purity_karat IS
  'NULL means not assessed. Never default this to 22 — an assumed purity would '
  'flow into valuation and misprice the pledge.';

CREATE INDEX IF NOT EXISTS loan_items_loan_id_idx ON public.loan_items (loan_id);

ALTER TABLE public.loan_items ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.loan_item_photos (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  loan_item_id  uuid NOT NULL REFERENCES public.loan_items (id) ON DELETE CASCADE,
  storage_path  text NOT NULL,
  caption       text,
  created_at    timestamptz NOT NULL DEFAULT timezone('utc', now()),

  -- Mirrors SAFE_STORAGE_PATH_RE in src/services/loanService.ts so a bad path
  -- cannot be persisted even if a future caller skips the client-side check.
  CONSTRAINT loan_item_photos_path_chk CHECK (
    storage_path ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/items/[A-Za-z0-9._-]+$'
  )
);

CREATE INDEX IF NOT EXISTS loan_item_photos_loan_item_id_idx
  ON public.loan_item_photos (loan_item_id);

ALTER TABLE public.loan_item_photos ENABLE ROW LEVEL SECURITY;

-- Backfill one item per existing loan. weight_grams is numeric(10,3); *1000 is
-- exact at that scale. purity_karat stays NULL (unknown, not assumed).
INSERT INTO public.loan_items (
  loan_id, ornament_type, description, gross_weight_mg, net_weight_mg, quantity
)
SELECT
  l.id,
  l.item_name,
  'Backfilled from loans.item_name / weight_grams by migration 20260815030000.',
  ROUND(l.weight_grams * 1000)::bigint,
  ROUND(l.weight_grams * 1000)::bigint,
  1
FROM public.loans l
WHERE NOT EXISTS (
  SELECT 1 FROM public.loan_items i WHERE i.loan_id = l.id
);

-- ---------------------------------------------------------------------------
-- 5. KYC on profiles + a private 'kyc' bucket
-- ---------------------------------------------------------------------------
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS date_of_birth date,
  ADD COLUMN IF NOT EXISTS id_document_type text,
  ADD COLUMN IF NOT EXISTS id_document_last4 text,
  ADD COLUMN IF NOT EXISTS id_document_path text,
  ADD COLUMN IF NOT EXISTS kyc_verified_on date,
  ADD COLUMN IF NOT EXISTS kyc_verified_by uuid REFERENCES public.profiles (id) ON DELETE RESTRICT,
  ADD COLUMN IF NOT EXISTS guardian_name text;

ALTER TABLE public.profiles
  DROP CONSTRAINT IF EXISTS profiles_id_document_type_chk;
ALTER TABLE public.profiles
  ADD CONSTRAINT profiles_id_document_type_chk CHECK (
    id_document_type IS NULL
    OR id_document_type IN ('aadhaar', 'pan', 'voter_id', 'driving_licence', 'passport')
  );

-- Last 4 only, never the full number in a queryable column.
ALTER TABLE public.profiles
  DROP CONSTRAINT IF EXISTS profiles_id_document_last4_chk;
ALTER TABLE public.profiles
  ADD CONSTRAINT profiles_id_document_last4_chk CHECK (
    id_document_last4 IS NULL OR id_document_last4 ~ '^[0-9A-Za-z]{4}$'
  );

-- Owner decision, enforced in the database rather than only in the UI:
-- an unmasked photo of an Aadhaar card IS the full 12-digit number, and UIDAI
-- forbids storing such a copy without redacting the first 8 digits. This shop
-- has no masking pipeline, so no Aadhaar image is ever stored.
ALTER TABLE public.profiles
  DROP CONSTRAINT IF EXISTS profiles_no_aadhaar_image_chk;
ALTER TABLE public.profiles
  ADD CONSTRAINT profiles_no_aadhaar_image_chk CHECK (
    id_document_type IS DISTINCT FROM 'aadhaar' OR id_document_path IS NULL
  );

COMMENT ON COLUMN public.profiles.id_document_path IS
  'Object path in the private ''kyc'' bucket, namespaced {customer_id}/... '
  'Must be NULL when id_document_type = ''aadhaar'' (UIDAI masking rule).';

ALTER TABLE public.profiles
  DROP CONSTRAINT IF EXISTS profiles_id_document_path_chk;
ALTER TABLE public.profiles
  ADD CONSTRAINT profiles_id_document_path_chk CHECK (
    id_document_path IS NULL
    OR id_document_path ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/[A-Za-z0-9._-]+$'
  );

-- A verification is meaningless without a verifier.
ALTER TABLE public.profiles
  DROP CONSTRAINT IF EXISTS profiles_kyc_verified_pair_chk;
ALTER TABLE public.profiles
  ADD CONSTRAINT profiles_kyc_verified_pair_chk CHECK (
    (kyc_verified_on IS NULL AND kyc_verified_by IS NULL)
    OR (kyc_verified_on IS NOT NULL AND kyc_verified_by IS NOT NULL)
  );

-- CURRENT_DATE is not immutable and so cannot appear in a CHECK; a static
-- floor is the most this constraint can honestly assert.
ALTER TABLE public.profiles
  DROP CONSTRAINT IF EXISTS profiles_date_of_birth_chk;
ALTER TABLE public.profiles
  ADD CONSTRAINT profiles_date_of_birth_chk CHECK (
    date_of_birth IS NULL OR date_of_birth > DATE '1900-01-01'
  );

-- A customer may read their own KYC fields but must never self-verify.
-- profiles_update_own allows a user to update their own row, so the restriction
-- has to live in a trigger.
CREATE OR REPLACE FUNCTION public.enforce_profile_kyc_permissions()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF public.is_shop_user() THEN
    RETURN NEW;
  END IF;

  IF NEW.kyc_verified_on IS DISTINCT FROM OLD.kyc_verified_on
     OR NEW.kyc_verified_by IS DISTINCT FROM OLD.kyc_verified_by
  THEN
    RAISE EXCEPTION 'only shop users may set KYC verification';
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS profiles_enforce_kyc_permissions ON public.profiles;
CREATE TRIGGER profiles_enforce_kyc_permissions
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW
  EXECUTE FUNCTION public.enforce_profile_kyc_permissions();

INSERT INTO storage.buckets (id, name, public)
VALUES ('kyc', 'kyc', false)
ON CONFLICT (id) DO NOTHING;

-- Never public, even if a previous run or the dashboard flipped it.
UPDATE storage.buckets SET public = false WHERE id = 'kyc';

DROP POLICY IF EXISTS "kyc_shop_select" ON storage.objects;
CREATE POLICY "kyc_shop_select"
  ON storage.objects FOR SELECT TO authenticated
  USING (bucket_id = 'kyc' AND public.is_shop_user());

DROP POLICY IF EXISTS "kyc_customer_select" ON storage.objects;
CREATE POLICY "kyc_customer_select"
  ON storage.objects FOR SELECT TO authenticated
  USING (
    bucket_id = 'kyc'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

DROP POLICY IF EXISTS "kyc_shop_insert" ON storage.objects;
CREATE POLICY "kyc_shop_insert"
  ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (
    bucket_id = 'kyc'
    AND public.is_shop_user()
    AND (storage.foldername(name))[1] ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
  );

DROP POLICY IF EXISTS "kyc_shop_update" ON storage.objects;
CREATE POLICY "kyc_shop_update"
  ON storage.objects FOR UPDATE TO authenticated
  USING (bucket_id = 'kyc' AND public.is_shop_user())
  WITH CHECK (
    bucket_id = 'kyc'
    AND public.is_shop_user()
    AND (storage.foldername(name))[1] ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
  );

DROP POLICY IF EXISTS "kyc_owner_delete" ON storage.objects;
CREATE POLICY "kyc_owner_delete"
  ON storage.objects FOR DELETE TO authenticated
  USING (bucket_id = 'kyc' AND public.is_owner());

-- ---------------------------------------------------------------------------
-- 6. Notices
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.loan_notices (
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  loan_id              uuid NOT NULL REFERENCES public.loans (id) ON DELETE CASCADE,
  notice_type          text NOT NULL,
  scheduled_for        date NOT NULL,
  sent_at              timestamptz,
  channel              text NOT NULL DEFAULT 'in_app',
  delivery_status      text NOT NULL DEFAULT 'pending',
  provider_message_id  text,
  payload              jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at           timestamptz NOT NULL DEFAULT timezone('utc', now()),

  CONSTRAINT loan_notices_type_chk CHECK (
    notice_type IN ('due_soon', 'overdue', 'renewal_offer', 'forfeiture_warning')
  ),
  CONSTRAINT loan_notices_channel_chk CHECK (channel IN ('sms', 'whatsapp', 'in_app')),
  CONSTRAINT loan_notices_delivery_status_chk CHECK (
    delivery_status IN ('pending', 'sent', 'delivered', 'failed', 'skipped')
  ),
  -- A notice is either unsent, or sent with a timestamp.
  CONSTRAINT loan_notices_sent_at_chk CHECK (
    (delivery_status IN ('sent', 'delivered') AND sent_at IS NOT NULL)
    OR delivery_status IN ('pending', 'failed', 'skipped')
  )
);

-- Idempotent notice generation: re-running a scheduler must not re-notify.
CREATE UNIQUE INDEX IF NOT EXISTS loan_notices_dedupe_idx
  ON public.loan_notices (loan_id, notice_type, scheduled_for);

CREATE INDEX IF NOT EXISTS loan_notices_scheduled_for_idx
  ON public.loan_notices (scheduled_for)
  WHERE sent_at IS NULL;

ALTER TABLE public.loan_notices ENABLE ROW LEVEL SECURITY;

-- Overdue determination is server-side. Never compare dates in JavaScript.
-- SECURITY INVOKER, so RLS decides the rows: shop users see every overdue loan,
-- a customer sees only their own.
CREATE OR REPLACE FUNCTION public.loans_overdue_as_of(
  p_as_of date DEFAULT ((timezone('Asia/Kolkata', now()))::date)
)
RETURNS TABLE (
  loan_id                      uuid,
  customer_id                  uuid,
  serial_number                text,
  disbursed_on                 date,
  due_on                       date,
  days_overdue                 integer,
  outstanding_principal_paise  bigint,
  accrued_interest_paise       bigint,
  total_due_paise              bigint
)
LANGUAGE sql
STABLE
SECURITY INVOKER
AS $$
  SELECT
    l.id,
    l.customer_id,
    l.serial_number,
    l.disbursed_on,
    (l.disbursed_on + l.simple_period_days)::date,
    (p_as_of - (l.disbursed_on + l.simple_period_days))::integer,
    b.outstanding_principal_paise,
    b.accrued_interest_paise,
    b.total_due_paise
  FROM public.loans l
  CROSS JOIN LATERAL public.loan_balances_as_of(l.id, p_as_of) b
  WHERE l.status = 'active'::public.loan_status
    AND p_as_of > (l.disbursed_on + l.simple_period_days)
  ORDER BY (l.disbursed_on + l.simple_period_days) ASC;
$$;

-- ---------------------------------------------------------------------------
-- 7. RLS for the new tables
--    Shape follows the existing loans/payments split: customer reads own via a
--    join to loans.customer_id, shop reads and writes, owner alone deletes.
-- ---------------------------------------------------------------------------
DROP POLICY IF EXISTS "loan_items_select_own" ON public.loan_items;
CREATE POLICY "loan_items_select_own"
  ON public.loan_items FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.loans l
      WHERE l.id = loan_items.loan_id AND l.customer_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "loan_items_shop_select" ON public.loan_items;
CREATE POLICY "loan_items_shop_select"
  ON public.loan_items FOR SELECT TO authenticated
  USING (public.is_shop_user());

DROP POLICY IF EXISTS "loan_items_shop_insert" ON public.loan_items;
CREATE POLICY "loan_items_shop_insert"
  ON public.loan_items FOR INSERT TO authenticated
  WITH CHECK (public.is_shop_user());

DROP POLICY IF EXISTS "loan_items_shop_update" ON public.loan_items;
CREATE POLICY "loan_items_shop_update"
  ON public.loan_items FOR UPDATE TO authenticated
  USING (public.is_shop_user())
  WITH CHECK (public.is_shop_user());

DROP POLICY IF EXISTS "loan_items_owner_delete" ON public.loan_items;
CREATE POLICY "loan_items_owner_delete"
  ON public.loan_items FOR DELETE TO authenticated
  USING (public.is_owner());

DROP POLICY IF EXISTS "loan_item_photos_select_own" ON public.loan_item_photos;
CREATE POLICY "loan_item_photos_select_own"
  ON public.loan_item_photos FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.loan_items i
      JOIN public.loans l ON l.id = i.loan_id
      WHERE i.id = loan_item_photos.loan_item_id
        AND l.customer_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "loan_item_photos_shop_select" ON public.loan_item_photos;
CREATE POLICY "loan_item_photos_shop_select"
  ON public.loan_item_photos FOR SELECT TO authenticated
  USING (public.is_shop_user());

DROP POLICY IF EXISTS "loan_item_photos_shop_insert" ON public.loan_item_photos;
CREATE POLICY "loan_item_photos_shop_insert"
  ON public.loan_item_photos FOR INSERT TO authenticated
  WITH CHECK (public.is_shop_user());

DROP POLICY IF EXISTS "loan_item_photos_shop_update" ON public.loan_item_photos;
CREATE POLICY "loan_item_photos_shop_update"
  ON public.loan_item_photos FOR UPDATE TO authenticated
  USING (public.is_shop_user())
  WITH CHECK (public.is_shop_user());

DROP POLICY IF EXISTS "loan_item_photos_owner_delete" ON public.loan_item_photos;
CREATE POLICY "loan_item_photos_owner_delete"
  ON public.loan_item_photos FOR DELETE TO authenticated
  USING (public.is_owner());

DROP POLICY IF EXISTS "loan_renewals_select_own" ON public.loan_renewals;
CREATE POLICY "loan_renewals_select_own"
  ON public.loan_renewals FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.loans l
      WHERE l.id = loan_renewals.loan_id AND l.customer_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "loan_renewals_shop_select" ON public.loan_renewals;
CREATE POLICY "loan_renewals_shop_select"
  ON public.loan_renewals FOR SELECT TO authenticated
  USING (public.is_shop_user());

-- Renewal is a lifecycle event: owner only, and the actor must be the caller.
DROP POLICY IF EXISTS "loan_renewals_insert_owner" ON public.loan_renewals;
CREATE POLICY "loan_renewals_insert_owner"
  ON public.loan_renewals FOR INSERT TO authenticated
  WITH CHECK (public.is_owner() AND renewed_by = auth.uid());

DROP POLICY IF EXISTS "loan_renewals_owner_delete" ON public.loan_renewals;
CREATE POLICY "loan_renewals_owner_delete"
  ON public.loan_renewals FOR DELETE TO authenticated
  USING (public.is_owner());

DROP POLICY IF EXISTS "loan_notices_select_own" ON public.loan_notices;
CREATE POLICY "loan_notices_select_own"
  ON public.loan_notices FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.loans l
      WHERE l.id = loan_notices.loan_id AND l.customer_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "loan_notices_shop_select" ON public.loan_notices;
CREATE POLICY "loan_notices_shop_select"
  ON public.loan_notices FOR SELECT TO authenticated
  USING (public.is_shop_user());

DROP POLICY IF EXISTS "loan_notices_shop_insert" ON public.loan_notices;
CREATE POLICY "loan_notices_shop_insert"
  ON public.loan_notices FOR INSERT TO authenticated
  WITH CHECK (public.is_shop_user());

DROP POLICY IF EXISTS "loan_notices_shop_update" ON public.loan_notices;
CREATE POLICY "loan_notices_shop_update"
  ON public.loan_notices FOR UPDATE TO authenticated
  USING (public.is_shop_user())
  WITH CHECK (public.is_shop_user());

DROP POLICY IF EXISTS "loan_notices_owner_delete" ON public.loan_notices;
CREATE POLICY "loan_notices_owner_delete"
  ON public.loan_notices FOR DELETE TO authenticated
  USING (public.is_owner());

-- ---------------------------------------------------------------------------
-- 8. Grants
--    The historical "GRANT ... ON ALL TABLES" only covered tables that existed
--    at that moment, so each new table needs its own grant or `authenticated`
--    is refused at the table level (42501) before RLS is ever consulted.
-- ---------------------------------------------------------------------------
GRANT SELECT, INSERT, UPDATE, DELETE ON public.loan_items TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.loan_item_photos TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.loan_renewals TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.loan_notices TO authenticated;

GRANT ALL ON public.loan_items TO postgres, service_role;
GRANT ALL ON public.loan_item_photos TO postgres, service_role;
GRANT ALL ON public.loan_renewals TO postgres, service_role;
GRANT ALL ON public.loan_notices TO postgres, service_role;

GRANT USAGE ON TYPE public.loan_status TO authenticated, service_role;

GRANT EXECUTE ON FUNCTION public.loans_overdue_as_of(date) TO authenticated, service_role;
